# permissions for end users to edit arithmetics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: arithmetic-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-controller-project
    app.kubernetes.io/part-of: k8s-controller-project
    app.kubernetes.io/managed-by: kustomize
  name: arithmetic-editor-role
rules:
- apiGroups:
  - maths.controller
  resources:
  - arithmetics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maths.controller
  resources:
  - arithmetics/status
  verbs:
  - get
